version: "3"
services: 
    dawumnam:
        container_name: dawumnam
        image: dawumnam/dawumnam
        restart: always
        build: .
        ports: 
            - "5000:5000"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes: 
            - ./data:/data/db
        ports: 
            - '27017:27017'